In [2]:
using Pkg
Pkg.status()
using SymPy
using BenchmarkTools, LinearAlgebra, LazyArrays, BandedMatrices

      Status `~/.julia/environments/v1.7/Project.toml`
  [aae01518] BandedMatrices v0.17.0
  [6e4b80f9] BenchmarkTools v1.3.1
  [8e7c35d0] BlockArrays v0.16.18
  [ce91de38] ColorBitstring v0.1.1
  [7073ff75] IJulia v1.23.3
  [5078a376] LazyArrays v0.22.10
  [a3b82374] MatrixFactorizations v0.9.1
  [91a5bcdd] Plots v1.29.0
  [438e738f] PyCall v1.93.1
  [295af30f] Revise v3.3.3
  [f8ebbe35] SemiseparableMatrices v0.3.3
  [3cc68bcd] SetRounding v0.2.1
  [24249f21] SymPy v1.1.6
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [8dfed614] Test


In [223]:
u1, u2, u3, u4, u5 = symbols("u_(1:6)", real=True)
x1, x2, x3, x4, x5 = symbols("x_(1:6)", real=True)
y1, y2, y3, y4, y5 = symbols("y_(1:6)", real=True)

a11, a12, a13, a14, a15 = symbols("a_1(1:6)", real=True)
a21, a22, a23, a24, a25 = symbols("a_2(1:6)", real=True)
a31, a32, a33, a34, a35 = symbols("a_3(1:6)", real=True)
a41, a42, a43, a44, a45 = symbols("a_4(1:6)", real=True)
a51, a52, a53, a54, a55 = symbols("a_5(1:6)", real=True)

u11, u12, u13, u14, u15 = symbols("u_1(1:6)", real=True)
u21, u22, u23, u24, u25 = symbols("u_2(1:6)", real=True)
u31, u32, u33, u34, u35 = symbols("u_3(1:6)", real=True)
u41, u42, u43, u44, u45 = symbols("u_4(1:6)", real=True)
u51, u52, u53, u54, u55 = symbols("u_5(1:6)", real=True)
# u1 = symbols("u^1_(1:6)", real=True)


# for i in 1:2
#     u$i = symbols("u_(1:6)^$i", real=True)
# end
# # u$i

# using Printf

# function genU(n, bw)

#     U = zeros(n, n)
#     for i in 1:n
#         for j in i:min(i+bw, n)
#             stri = string(i)
#             strj = string(j)
#             # str = "u_$i$j"
#             # display("$i$j")
#             U[i, j] = symbols(println("u_$j^$i"), real=True)
#         end
#     end
#     U
# end
# genU(10, 1)
# # u1[1]

(u_51, u_52, u_53, u_54, u_55)

In [248]:
dv = [1, 1, 1, 1]
ev = [u1, u2, u3]
U = Bidiagonal(dv, ev, :U)


U = [1 u1 0 0 ;
     0 1 u2 0 ;
     0 0 1 u3 ;
     0 0 0 1  ]


4×4 Matrix{Sym}:
 1  u₁    0    0
 0    1  u₂    0
 0    0    1  u₃
 0    0    0    1

In [266]:
function ppl(context)
    println(sympy.latex(context))
end

uu0 = symbols("u^0_(1:6)", real=True)
uu1 = symbols("u^1_(1:5)", real=True)

uu0 = [i for i in uu0]
uu1 = [i for i in uu1]


AA = Bidiagonal(uu0, uu1, :U)

# DD = Diagonal(1 ./ uu0)

# AA*DD - DD*AA


# ppl(U)

5×5 Bidiagonal{Sym, Vector{Sym}}:
 u⁰₁  u¹₁      ⋅      ⋅      ⋅
     ⋅  u⁰₂  u¹₂      ⋅      ⋅
     ⋅      ⋅  u⁰₃  u¹₃      ⋅
     ⋅      ⋅      ⋅  u⁰₄  u¹₄
     ⋅      ⋅      ⋅      ⋅  u⁰₅

In [253]:
x = [x1, x2, x3, x4]
y = [y1, y2, y3, y4]
A = [a11 a12 a13 a14 ;
     a21 a22 a23 a24 ;
     a31 a32 a33 a34 ;
     a41 a42 a43 a44 ]

A = triu(A, 0)
display(A)

A1 = triu(x * y', 0)
display(A1)


4×4 Matrix{Sym}:
 a₁₁  a₁₂  a₁₃  a₁₄
    0  a₂₂  a₂₃  a₂₄
    0     0  a₃₃  a₃₄
    0     0     0  a₄₄

4×4 Matrix{Sym}:
 x₁⋅y₁  x₁⋅y₂  x₁⋅y₃  x₁⋅y₄
       0  x₂⋅y₂  x₂⋅y₃  x₂⋅y₄
       0        0  x₃⋅y₃  x₃⋅y₄
       0        0        0  x₄⋅y₄

In [226]:
U * A

4×4 Matrix{Sym}:
 a₁₁  a₁₂ + a₂₂⋅u₁  a₁₃ + a₂₃⋅u₁  a₁₄ + a₂₄⋅u₁
    0             a₂₂  a₂₃ + a₃₃⋅u₂  a₂₄ + a₃₄⋅u₂
    0                0             a₃₃  a₃₄ + a₄₄⋅u₃
    0                0                0             a₄₄

In [7]:
@vars a b c d

(a, b, c, d)

In [8]:
e4 = [0, 0, 0, 1]
e4 * y'

4×4 Matrix{Sym}:
   0    0    0    0
   0    0    0    0
   0    0    0    0
 y₁  y₂  y₃  y₄

In [9]:
A11 = U
B11 = e4

X11 = A11 \ B11

triu(A11 * X11 * (1 ./ X11)', 1)


4×4 Matrix{Sym}:
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [10]:
triu(X11 * (1 ./ X11)', 0)

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂  -u₁⋅u₂⋅u₃
 0     1     -u₂       u₂⋅u₃
 0     0        1          -u₃
 0     0        0             1

In [11]:
inv(U)

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂  -u₁⋅u₂⋅u₃
 0     1     -u₂       u₂⋅u₃
 0     0        1          -u₃
 0     0        0             1

In [12]:
size(U)[1]

4

In [411]:
function backSub(U, b)
    n = size(U)[1]
    x = zeros(n)
    x[end] = b[end] / U[end, end]
    for i in n-1 : -1 : 1
        sum_ = 0.0
        for j in i+1 : n
            sum_ += U[i, j] * x[j]
        end
        x[i] = (b[i] - sum_)/U[i, i]
    end
    x
end

function backSubBanded(U, b, bw=1)
    T = eltype(U)
    n = size(U)[1]
    x = zeros(T, n)
    x[end] = b[end] / U[end, end]

    for i in n-1 : -1 : 1
        sum_ = zero(T)
        for j in i+1 : min(n, i+bw)
            sum_ += U[i, j] * x[j]
        end
        x[i] = (b[i] - sum_) / U[i, i]

    end
    x
end


function backSubBandedBF(U, b, bw=1)
    n = size(U)[1]
    x = zeros(n)
    for i in 1:n
        x[i] = BigFloat(0.0)
    end
    x[end] = BigFloat(b[end]) / BigFloat(U[end, end])
    for i in n-1 : -1 : 1
        sum_ = BigFloat(0.0)
        for j in i+1 : min(n, i+bw)
            sum_ += BigFloat(U[i, j]) * BigFloat(x[j])
        end
        x[i] = (BigFloat(b[i]) - BigFloat(sum_)) / BigFloat(U[i, i])
    end
    x
end

function backSubBandedBFboardcast(U, b, bw=1)
    n = size(U)[1]
    x = BigFloat.(zeros(n))
    x[end] = BigFloat.(b[end] / U[end, end])
    for i in n-1 : -1 : 1
        sum_ = BigFloat(0.0)
        for j in i+1 : min(n, i+bw)
            sum_ += BigFloat.(U[i, j] * x[j])
        end
        x[i] = BigFloat.((b[i] - sum_) / U[i, i])
    end
    x
end

using Random
Random.seed!(0);


n = 10000
bw = 1
U = BandedMatrix(rand(n, n), (0, bw))

U = Bidiagonal(1 .+ BigFloat.(rand(n)), BigFloat.(rand(n-1)), :U)

b = BigFloat.(rand(n))
# x = BigFloat.(rand(n))
# x = zeros(BigFloat, n)
# x[end] = BigFloat(1.0)

# b = U * x

display(norm((U \ b)))
display(norm(backSubBanded(U, b, bw)))
display(norm(backSubBandedBF(U, b, bw)))
display(norm(backSubBandedBFboardcast(U, b, bw)))
display("-------------------------")


# abserror = np.linalg.norm(corr - approx)
# relerror = abserror/np.linalg.norm(corr)


display(norm((big.(U) \ b) - backSubBanded(U, b, bw)))
display(norm((big.(U) \ b) - backSubBandedBF(U, b, bw)))
display(norm((big.(U) \ b) - backSubBandedBFboardcast(U, b, bw)))


@time U \ b
@time backSubBanded(U, b, bw);
@time backSubBandedBF(U, b, bw);
@time backSubBandedBFboardcast(U, b, bw);

35.15402481018372601771167248982052643908642408306572046390187348945877222932595

35.15402481018372601771167248982052643908642408306572046390187348945877222932595

35.1540248101837

35.15402481018372601771167248982052643908642408306572046390187348945877222932595

"-------------------------"

0.0

1.800412155365235041586851169022533693704130233631326639507964447862194377489943e-15

0.0

  0.003132 seconds (60.02 k allocations: 3.281 MiB)
  0.003560 seconds (100.00 k allocations: 5.417 MiB)
  0.004136 seconds (139.99 k allocations: 7.553 MiB)
  0.003913 seconds (120.00 k allocations: 6.561 MiB)


In [398]:
n = 1000
bw = 1
U = BandedMatrix(rand(n, n), (0, bw))
U = brand(n, n, 0, bw)
U = Bidiagonal(BigFloat.(ones(n)), BigFloat.(rand(n-1)), :U)


function invBiU(U)
    n = size(U)[1]
    e_n = zeros(n)
    e_n[n] = 1.0
    # x = U \ e_n
    x = backSubBanded(U, b, 1)
    y = 1 ./ x
    Uinv = triu(x * y', 0)
end

function invBiUBF(U)
    n = size(U)[1]
    e_n = zeros(n)
    for i in 1:n-1
        e_n[i] = BigFloat(0.0)
    end
    e_n[n] = BigFloat(1.0)
    # x = U \ e_n
    x = backSubBandedBF(U, b, 1)
    y = zeros(n)
    for i in 1:n
        y[i] = BigFloat(1) / BigFloat(x[i])
    end
    Uinv = triu(x * y', 0)
end

function invBiUBFboardcast(U)
    n = size(U)[1]
    e_n = BigFloat.(zeros(n))
    e_n[n] = BigFloat.(1.0)
    # x = U \ e_n
    x = backSubBandedBFboardcast(U, b, 1)
    y = BigFloat.(1 ./ x)
    Uinv = triu(BigFloat.(x) * BigFloat.(y'), 0)
end


@time inv(U)
@time invBiU(U)
@time invBiUBF(U)
@time invBiUBFboardcast(U)

@show U \ b

display(norm(invBiU(U) - inv(U)))
display(norm(invBiUBF(U) - inv(U)))
display(norm(invBiUBFboardcast(U) - inv(U)))

# invBiU(U)

  0.155115 seconds (6.00 M allocations: 327.859 MiB)
  0.169652 seconds (3.17 M allocations: 184.781 MiB, 15.63% compilation time)
  0.022963 seconds (112.86 k allocations: 21.368 MiB, 86.84% compilation time)
  0.532454 seconds (13.26 M allocations: 723.360 MiB, 45.45% gc time, 7.82% compilation time)


LoadError: DimensionMismatch("second dimension of A, 1000, does not match one of the lengths of x, 10000, or b, 10000")

In [16]:
x11, x12, x13, x14, x15 = symbols("x_1(1:6)", real=True)
y11, y12, y13, y14, y15 = symbols("y_1(1:6)", real=True)
x21, x22, x23, x24, x25 = symbols("x_2(1:6)", real=True)
y21, y22, y23, y24, y25 = symbols("y_2(1:6)", real=True)

(y_21, y_22, y_23, y_24, y_25)

In [287]:
x1 = [x11, x12, x13, x14]
x2 = [x21, x22, x23, x24]
y1 = [y11, y12, y13, y14]
y2 = [y21, y22, y23, y24]
y1p = [0,0,0,0]
x1p = [1,1,1,1]

e3 = [0,0,1,0]
e4 = [0,0,0,1]
triu([e3 e4] * [y1 y2]', 1)
# triu([e3 e4] * [y1p y2]', 1)


triu([x1 x2] * [y1 y2]')



# triu([x1p x2] * [y1p y2]')
display(U * triu(x1 * y1'))

display(U * x1 * y1')

display(triu(U * x1 * y1'))

triu(U * x1 * y1') - U * triu(x1 * y1')


4×4 Matrix{Sym}:
 x₁₁⋅y₁₁  …  u₁⋅x₁₂⋅y₁₄ + u₄⋅x₁₃⋅y₁₄ + x₁₁⋅y₁₄
         0     u₂⋅x₁₃⋅y₁₄ + u₅⋅x₁₄⋅y₁₄ + x₁₂⋅y₁₄
         0                     u₃⋅x₁₄⋅y₁₄ + x₁₃⋅y₁₄
         0                                     x₁₄⋅y₁₄

4×4 Matrix{Sym}:
 y₁₁⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)  …  y₁₄⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)
 y₁₁⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)     y₁₄⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)
            y₁₁⋅(u₃⋅x₁₄ + x₁₃)                y₁₄⋅(u₃⋅x₁₄ + x₁₃)
                         x₁₄⋅y₁₁                             x₁₄⋅y₁₄

4×4 Matrix{Sym}:
 y₁₁⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)  …  y₁₄⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)
                                 0     y₁₄⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)
                                 0                y₁₄⋅(u₃⋅x₁₄ + x₁₃)
                                 0                             x₁₄⋅y₁₄

4×4 Matrix{Sym}:
 -x₁₁⋅y₁₁ + y₁₁⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)  …  -u₁⋅x₁₂⋅y₁₄ - u₄⋅x₁₃⋅y₁₄ - x₁₁⋅y₁₄ + y₁₄⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)
                                              0     -u₂⋅x₁₃⋅y₁₄ - u₅⋅x₁₄⋅y₁₄ - x₁₂⋅y₁₄ + y₁₄⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)
                                              0                                -u₃⋅x₁₄⋅y₁₄ - x₁₃⋅y₁₄ + y₁₄⋅(u₃⋅x₁₄ + x₁₃)
                                              0                                                                                  0

In [272]:
U = [1 u1 u4 0 ;
     0 1 u2 u5 ;
     0 0 1 u3 ;
     0 0 0 1  ]
display(U)
A = [a11 a12 a13 a14 ;
     a21 a22 a23 a24 ;
     a31 a32 a33 a34 ;
     a41 a42 a43 a44 ]

A = triu(A, 0)
display(A)

U * A 
inv(U)

4×4 Matrix{Sym}:
 1  u₁  u₄    0
 0    1  u₂  u₅
 0    0    1  u₃
 0    0    0    1

4×4 Matrix{Sym}:
 a₁₁  a₁₂  a₁₃  a₁₄
    0  a₂₂  a₂₃  a₂₄
    0     0  a₃₃  a₃₄
    0     0     0  a₄₄

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂ - u₄  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
 0     1           -u₂                     u₂⋅u₃ - u₅
 0     0              1                              -u₃
 0     0              0                                 1

In [281]:
e4 = [0, 0, 0, 1]
e3 = [0, 0, 1, 0]


display(U \ [e3 e4])

x1 = U \ e4
x2 = U \ e3
display(x1)
display(x2)
y1 = 1 ./ x1
y1[1:end-1] ./= 2
# y1 = [0,0,0,0]
y2 = 1 ./ x2
y2 ./= 2
y2[end] = 0

# y2 = [0,0,0,0]
# y2[end]=0
# y1 = [y11, y12, y13, y14]
# y2 = [y21, y22, y23, y24]


# U * [x2 x1] * [y2 y1]'
A = [x2 x1] * [y2 y1]'
display(A)
display(inv(U))

triu(A) - inv(U)

# X = [x2 x1]
# UX = U * X


# triu(x2 * (1 ./ x2)', )

# [e3 e4] * [y2 y1]'
# [e4 e3] * [y2 y1]'

4×2 Matrix{Sym}:
 u₁⋅u₂ - u₄  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
          -u₂                     u₂⋅u₃ - u₅
             1                              -u₃
             0                                 1

4-element Vector{Sym}:
 -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
                    u₂⋅u₃ - u₅
                             -u₃
                                1

4-element Vector{Sym}:
 u₁⋅u₂ - u₄
          -u₂
             1
             0

4×4 Matrix{Sym}:
                                                                                 1  …  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
 -u_2/(2*(u_1*u_2 - u_4)) + (u_2*u_3 - u_5)/(2*(-u_1*u_2*u_3 + u_1*u_5 + u_3*u_4))                        u₂⋅u₃ - u₅
               -u_3/(2*(-u_1*u_2*u_3 + u_1*u_5 + u_3*u_4)) + 1/(2*(u_1*u_2 - u_4))                                 -u₃
                                          1/(2*(-u_1*u_2*u_3 + u_1*u_5 + u_3*u_4))                                    1

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂ - u₄  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
 0     1           -u₂                     u₂⋅u₃ - u₅
 0     0              1                              -u₃
 0     0              0                                 1

4×4 Matrix{Sym}:
 0  …  0
 0     0
 0     0
 0     0

In [ ]:
triu(x1 * (1 ./ x1)')

4×4 Matrix{Sym}:
 1  …  -u₁₁⋅u₂₁⋅u₃₁ + u₁₁⋅u₂₂ + u₁₂⋅u₃₁
 0                            u₂₁⋅u₃₁ - u₂₂
 0                                       -u₃₁
 0                                           1

In [ ]:
triu(x2 * (1 ./ x2)')

4×4 Matrix{Sym}:
 1  -(u_11*u_21 - u_12)/u_21  …  (u_11*u_21 - u_12)*conjugate(zoo)
 0                         1                  -u_21*conjugate(zoo)
 0                         0                        conjugate(zoo)
 0                         0                                     0

In [146]:
println(sympy.latex(triu(x2 * (1 ./ x2)')))

\left[\begin{matrix}1 & \frac{x_{21}}{x_{22}} & \frac{x_{21}}{x_{23}} & \frac{x_{21}}{x_{24}}\\0 & 1 & \frac{x_{22}}{x_{23}} & \frac{x_{22}}{x_{24}}\\0 & 0 & 1 & \frac{x_{23}}{x_{24}}\\0 & 0 & 0 & 1\end{matrix}\right]


ppl (generic function with 1 method)

In [149]:
ppl(A)

\left[\begin{matrix}a_{11} & a_{12} & a_{13} & a_{14}\\0 & a_{22} & a_{23} & a_{24}\\0 & 0 & a_{33} & a_{34}\\0 & 0 & 0 & a_{44}\end{matrix}\right]


In [4]:
n = 2*30
bw = 2
U = BandedMatrix(rand(n, n), (0, bw))
U += I

display(cond(U))
# for i in 1:n
#     U[i, i] = 1.0
# end
# display(U)


E2 = zeros(n, 2)

E2[end-1:end, :] = [1 0 ; 0 1]
X = U \ E2
Yt = zeros(2, n)
Yt[:, n-1:n] = [1 0 ; 0 1]


# display(X)
for i in n-3 : -2 : 1
    # println((i, i+1))
    Xi = X[i:i+1, :]
    Di = U[i:i+1, i:i+1]
    Yti = inv(Xi) * inv(Di)
    Yt[:, i:i+1] = Yti
    # display(Di)
end 







display(triu(X * Yt) * U ≈ I)

norm(triu(X * Yt) * U - I)
# triu(X * Yt) - inv(U)
# Y1 = inv(X1) * inv(D1)

# A = vcat([1 2], [1 2])

4.909008704613903

false

1.8206055085334482e-5

In [80]:
function InvseBidiagonalUpper(U)
    T = eltype(U)
    n = size(U)[2]
    e_n = zeros(T, n)
    e_n[n] = one(T)
    x = BandedBackwardSubstitution(U, e_n, 1)
    y = inv.(U[diagind(U)] .* x)
    Uinv = triu(x * y')
    Uinv
end


function MakeI(n, T)
    I_ = zeros(T, n, n)
    I_[diagind(I_)] .= one(T)
    I_
end

function invTriU(U)
    T = eltype(U)
    n = size(U)[2]
    bw = 2
    E_n = zeros(T, n-bw, bw)
    E_n = vcat(E_n, MakeI(bw, T))
    # E_n = [E_n ; MakeI(bw, T)]
    println(typeof(E_n))


end

invTriU(U)


n = 2*30
bw = 2
U = big.(BandedMatrix(rand(n, n), (0, bw)))
U += I

# display(cond(U))
# # for i in 1:n
# #     U[i, i] = 1.0
# # end
# # display(U)


# E2 = zeros(n, 2)

# E2[end-1:end, :] = [1 0 ; 0 1]
# X = U \ E2
# Yt = zeros(2, n)
# Yt[:, n-1:n] = [1 0 ; 0 1]


# # display(X)
# for i in n-3 : -2 : 1
#     # println((i, i+1))
#     Xi = X[i:i+1, :]
#     Di = U[i:i+1, i:i+1]
#     Yti = inv(Xi) * inv(Di)
#     Yt[:, i:i+1] = Yti
#     # display(Di)
# end 


# display(triu(X * Yt) * U ≈ I)

# norm(triu(X * Yt) * U - I)
# triu(X * Yt) - inv(U)
# Y1 = inv(X1) * inv(D1)

# A = vcat([1 2], [1 2])

MakeI(3, BigFloat)

Matrix{BigFloat}


3×3 Matrix{BigFloat}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [20]:
n = 2*30
bw = 2
U = big.(BandedMatrix(rand(n, n), (0, bw)))
U += I
T = eltype(U)
n = size(U)[2]
bw = 2
E_k = one(U)[:, n-bw+1:n]
X = U \ E_k
# size(A)[1]

LoadError: UndefVarError: banded_lufact! not defined

In [71]:
n = 2*100
bw = 2
U = BandedMatrix(rand(n, n), (0, bw))
bandwidths(U)


LoadError: UndefVarError: eyes not defined