In [2]:
using Pkg
Pkg.status()
using SymPy
using BenchmarkTools, LinearAlgebra, LazyArrays, BandedMatrices

      Status `~/.julia/environments/v1.7/Project.toml`
  [aae01518] BandedMatrices v0.17.0
  [6e4b80f9] BenchmarkTools v1.3.1
  [ce91de38] ColorBitstring v0.1.1
  [7073ff75] IJulia v1.23.3
  [5078a376] LazyArrays v0.22.10
  [a3b82374] MatrixFactorizations v0.9.1
  [91a5bcdd] Plots v1.29.0
  [438e738f] PyCall v1.93.1
  [295af30f] Revise v3.3.3
  [f8ebbe35] SemiseparableMatrices v0.3.3
  [3cc68bcd] SetRounding v0.2.1
  [24249f21] SymPy v1.1.6
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [8dfed614] Test


In [223]:
u1, u2, u3, u4, u5 = symbols("u_(1:6)", real=True)
x1, x2, x3, x4, x5 = symbols("x_(1:6)", real=True)
y1, y2, y3, y4, y5 = symbols("y_(1:6)", real=True)

a11, a12, a13, a14, a15 = symbols("a_1(1:6)", real=True)
a21, a22, a23, a24, a25 = symbols("a_2(1:6)", real=True)
a31, a32, a33, a34, a35 = symbols("a_3(1:6)", real=True)
a41, a42, a43, a44, a45 = symbols("a_4(1:6)", real=True)
a51, a52, a53, a54, a55 = symbols("a_5(1:6)", real=True)

u11, u12, u13, u14, u15 = symbols("u_1(1:6)", real=True)
u21, u22, u23, u24, u25 = symbols("u_2(1:6)", real=True)
u31, u32, u33, u34, u35 = symbols("u_3(1:6)", real=True)
u41, u42, u43, u44, u45 = symbols("u_4(1:6)", real=True)
u51, u52, u53, u54, u55 = symbols("u_5(1:6)", real=True)
# u1 = symbols("u^1_(1:6)", real=True)


# for i in 1:2
#     u$i = symbols("u_(1:6)^$i", real=True)
# end
# # u$i

# using Printf

# function genU(n, bw)

#     U = zeros(n, n)
#     for i in 1:n
#         for j in i:min(i+bw, n)
#             stri = string(i)
#             strj = string(j)
#             # str = "u_$i$j"
#             # display("$i$j")
#             U[i, j] = symbols(println("u_$j^$i"), real=True)
#         end
#     end
#     U
# end
# genU(10, 1)
# # u1[1]

(u_51, u_52, u_53, u_54, u_55)

In [248]:
dv = [1, 1, 1, 1]
ev = [u1, u2, u3]
U = Bidiagonal(dv, ev, :U)


U = [1 u1 0 0 ;
     0 1 u2 0 ;
     0 0 1 u3 ;
     0 0 0 1  ]


4×4 Matrix{Sym}:
 1  u₁    0    0
 0    1  u₂    0
 0    0    1  u₃
 0    0    0    1

In [266]:
function ppl(context)
    println(sympy.latex(context))
end

uu0 = symbols("u^0_(1:6)", real=True)
uu1 = symbols("u^1_(1:5)", real=True)

uu0 = [i for i in uu0]
uu1 = [i for i in uu1]


AA = Bidiagonal(uu0, uu1, :U)

# DD = Diagonal(1 ./ uu0)

# AA*DD - DD*AA


# ppl(U)

5×5 Bidiagonal{Sym, Vector{Sym}}:
 u⁰₁  u¹₁      ⋅      ⋅      ⋅
     ⋅  u⁰₂  u¹₂      ⋅      ⋅
     ⋅      ⋅  u⁰₃  u¹₃      ⋅
     ⋅      ⋅      ⋅  u⁰₄  u¹₄
     ⋅      ⋅      ⋅      ⋅  u⁰₅

In [253]:
x = [x1, x2, x3, x4]
y = [y1, y2, y3, y4]
A = [a11 a12 a13 a14 ;
     a21 a22 a23 a24 ;
     a31 a32 a33 a34 ;
     a41 a42 a43 a44 ]

A = triu(A, 0)
display(A)

A1 = triu(x * y', 0)
display(A1)


4×4 Matrix{Sym}:
 a₁₁  a₁₂  a₁₃  a₁₄
    0  a₂₂  a₂₃  a₂₄
    0     0  a₃₃  a₃₄
    0     0     0  a₄₄

4×4 Matrix{Sym}:
 x₁⋅y₁  x₁⋅y₂  x₁⋅y₃  x₁⋅y₄
       0  x₂⋅y₂  x₂⋅y₃  x₂⋅y₄
       0        0  x₃⋅y₃  x₃⋅y₄
       0        0        0  x₄⋅y₄

In [226]:
U * A

4×4 Matrix{Sym}:
 a₁₁  a₁₂ + a₂₂⋅u₁  a₁₃ + a₂₃⋅u₁  a₁₄ + a₂₄⋅u₁
    0             a₂₂  a₂₃ + a₃₃⋅u₂  a₂₄ + a₃₄⋅u₂
    0                0             a₃₃  a₃₄ + a₄₄⋅u₃
    0                0                0             a₄₄

In [7]:
@vars a b c d

(a, b, c, d)

In [8]:
e4 = [0, 0, 0, 1]
e4 * y'

4×4 Matrix{Sym}:
   0    0    0    0
   0    0    0    0
   0    0    0    0
 y₁  y₂  y₃  y₄

In [9]:
A11 = U
B11 = e4

X11 = A11 \ B11

triu(A11 * X11 * (1 ./ X11)', 1)


4×4 Matrix{Sym}:
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [10]:
triu(X11 * (1 ./ X11)', 0)

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂  -u₁⋅u₂⋅u₃
 0     1     -u₂       u₂⋅u₃
 0     0        1          -u₃
 0     0        0             1

In [11]:
inv(U)

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂  -u₁⋅u₂⋅u₃
 0     1     -u₂       u₂⋅u₃
 0     0        1          -u₃
 0     0        0             1

In [12]:
size(U)[1]

4

In [411]:
function backSub(U, b)
    n = size(U)[1]
    x = zeros(n)
    x[end] = b[end] / U[end, end]
    for i in n-1 : -1 : 1
        sum_ = 0.0
        for j in i+1 : n
            sum_ += U[i, j] * x[j]
        end
        x[i] = (b[i] - sum_)/U[i, i]
    end
    x
end

function backSubBanded(U, b, bw=1)
    T = eltype(U)
    n = size(U)[1]
    x = zeros(T, n)
    x[end] = b[end] / U[end, end]

    for i in n-1 : -1 : 1
        sum_ = zero(T)
        for j in i+1 : min(n, i+bw)
            sum_ += U[i, j] * x[j]
        end
        x[i] = (b[i] - sum_) / U[i, i]

    end
    x
end


function backSubBandedBF(U, b, bw=1)
    n = size(U)[1]
    x = zeros(n)
    for i in 1:n
        x[i] = BigFloat(0.0)
    end
    x[end] = BigFloat(b[end]) / BigFloat(U[end, end])
    for i in n-1 : -1 : 1
        sum_ = BigFloat(0.0)
        for j in i+1 : min(n, i+bw)
            sum_ += BigFloat(U[i, j]) * BigFloat(x[j])
        end
        x[i] = (BigFloat(b[i]) - BigFloat(sum_)) / BigFloat(U[i, i])
    end
    x
end

function backSubBandedBFboardcast(U, b, bw=1)
    n = size(U)[1]
    x = BigFloat.(zeros(n))
    x[end] = BigFloat.(b[end] / U[end, end])
    for i in n-1 : -1 : 1
        sum_ = BigFloat(0.0)
        for j in i+1 : min(n, i+bw)
            sum_ += BigFloat.(U[i, j] * x[j])
        end
        x[i] = BigFloat.((b[i] - sum_) / U[i, i])
    end
    x
end

using Random
Random.seed!(0);


n = 10000
bw = 1
U = BandedMatrix(rand(n, n), (0, bw))

U = Bidiagonal(1 .+ BigFloat.(rand(n)), BigFloat.(rand(n-1)), :U)

b = BigFloat.(rand(n))
# x = BigFloat.(rand(n))
# x = zeros(BigFloat, n)
# x[end] = BigFloat(1.0)

# b = U * x

display(norm((U \ b)))
display(norm(backSubBanded(U, b, bw)))
display(norm(backSubBandedBF(U, b, bw)))
display(norm(backSubBandedBFboardcast(U, b, bw)))
display("-------------------------")


# abserror = np.linalg.norm(corr - approx)
# relerror = abserror/np.linalg.norm(corr)


display(norm((big.(U) \ b) - backSubBanded(U, b, bw)))
display(norm((big.(U) \ b) - backSubBandedBF(U, b, bw)))
display(norm((big.(U) \ b) - backSubBandedBFboardcast(U, b, bw)))


@time U \ b
@time backSubBanded(U, b, bw);
@time backSubBandedBF(U, b, bw);
@time backSubBandedBFboardcast(U, b, bw);

35.15402481018372601771167248982052643908642408306572046390187348945877222932595

35.15402481018372601771167248982052643908642408306572046390187348945877222932595

35.1540248101837

35.15402481018372601771167248982052643908642408306572046390187348945877222932595

"-------------------------"

0.0

1.800412155365235041586851169022533693704130233631326639507964447862194377489943e-15

0.0

  0.003132 seconds (60.02 k allocations: 3.281 MiB)
  0.003560 seconds (100.00 k allocations: 5.417 MiB)
  0.004136 seconds (139.99 k allocations: 7.553 MiB)
  0.003913 seconds (120.00 k allocations: 6.561 MiB)


In [398]:
n = 1000
bw = 1
U = BandedMatrix(rand(n, n), (0, bw))
U = brand(n, n, 0, bw)
U = Bidiagonal(BigFloat.(ones(n)), BigFloat.(rand(n-1)), :U)


function invBiU(U)
    n = size(U)[1]
    e_n = zeros(n)
    e_n[n] = 1.0
    # x = U \ e_n
    x = backSubBanded(U, b, 1)
    y = 1 ./ x
    Uinv = triu(x * y', 0)
end

function invBiUBF(U)
    n = size(U)[1]
    e_n = zeros(n)
    for i in 1:n-1
        e_n[i] = BigFloat(0.0)
    end
    e_n[n] = BigFloat(1.0)
    # x = U \ e_n
    x = backSubBandedBF(U, b, 1)
    y = zeros(n)
    for i in 1:n
        y[i] = BigFloat(1) / BigFloat(x[i])
    end
    Uinv = triu(x * y', 0)
end

function invBiUBFboardcast(U)
    n = size(U)[1]
    e_n = BigFloat.(zeros(n))
    e_n[n] = BigFloat.(1.0)
    # x = U \ e_n
    x = backSubBandedBFboardcast(U, b, 1)
    y = BigFloat.(1 ./ x)
    Uinv = triu(BigFloat.(x) * BigFloat.(y'), 0)
end


@time inv(U)
@time invBiU(U)
@time invBiUBF(U)
@time invBiUBFboardcast(U)

@show U \ b

display(norm(invBiU(U) - inv(U)))
display(norm(invBiUBF(U) - inv(U)))
display(norm(invBiUBFboardcast(U) - inv(U)))

# invBiU(U)

  0.155115 seconds (6.00 M allocations: 327.859 MiB)
  0.169652 seconds (3.17 M allocations: 184.781 MiB, 15.63% compilation time)
  0.022963 seconds (112.86 k allocations: 21.368 MiB, 86.84% compilation time)
  0.532454 seconds (13.26 M allocations: 723.360 MiB, 45.45% gc time, 7.82% compilation time)


LoadError: DimensionMismatch("second dimension of A, 1000, does not match one of the lengths of x, 10000, or b, 10000")

In [16]:
x11, x12, x13, x14, x15 = symbols("x_1(1:6)", real=True)
y11, y12, y13, y14, y15 = symbols("y_1(1:6)", real=True)
x21, x22, x23, x24, x25 = symbols("x_2(1:6)", real=True)
y21, y22, y23, y24, y25 = symbols("y_2(1:6)", real=True)

(y_21, y_22, y_23, y_24, y_25)

In [287]:
x1 = [x11, x12, x13, x14]
x2 = [x21, x22, x23, x24]
y1 = [y11, y12, y13, y14]
y2 = [y21, y22, y23, y24]
y1p = [0,0,0,0]
x1p = [1,1,1,1]

e3 = [0,0,1,0]
e4 = [0,0,0,1]
triu([e3 e4] * [y1 y2]', 1)
# triu([e3 e4] * [y1p y2]', 1)


triu([x1 x2] * [y1 y2]')



# triu([x1p x2] * [y1p y2]')
display(U * triu(x1 * y1'))

display(U * x1 * y1')

display(triu(U * x1 * y1'))

triu(U * x1 * y1') - U * triu(x1 * y1')


4×4 Matrix{Sym}:
 x₁₁⋅y₁₁  …  u₁⋅x₁₂⋅y₁₄ + u₄⋅x₁₃⋅y₁₄ + x₁₁⋅y₁₄
         0     u₂⋅x₁₃⋅y₁₄ + u₅⋅x₁₄⋅y₁₄ + x₁₂⋅y₁₄
         0                     u₃⋅x₁₄⋅y₁₄ + x₁₃⋅y₁₄
         0                                     x₁₄⋅y₁₄

4×4 Matrix{Sym}:
 y₁₁⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)  …  y₁₄⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)
 y₁₁⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)     y₁₄⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)
            y₁₁⋅(u₃⋅x₁₄ + x₁₃)                y₁₄⋅(u₃⋅x₁₄ + x₁₃)
                         x₁₄⋅y₁₁                             x₁₄⋅y₁₄

4×4 Matrix{Sym}:
 y₁₁⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)  …  y₁₄⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)
                                 0     y₁₄⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)
                                 0                y₁₄⋅(u₃⋅x₁₄ + x₁₃)
                                 0                             x₁₄⋅y₁₄

4×4 Matrix{Sym}:
 -x₁₁⋅y₁₁ + y₁₁⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)  …  -u₁⋅x₁₂⋅y₁₄ - u₄⋅x₁₃⋅y₁₄ - x₁₁⋅y₁₄ + y₁₄⋅(u₁⋅x₁₂ + u₄⋅x₁₃ + x₁₁)
                                              0     -u₂⋅x₁₃⋅y₁₄ - u₅⋅x₁₄⋅y₁₄ - x₁₂⋅y₁₄ + y₁₄⋅(u₂⋅x₁₃ + u₅⋅x₁₄ + x₁₂)
                                              0                                -u₃⋅x₁₄⋅y₁₄ - x₁₃⋅y₁₄ + y₁₄⋅(u₃⋅x₁₄ + x₁₃)
                                              0                                                                                  0

In [272]:
U = [1 u1 u4 0 ;
     0 1 u2 u5 ;
     0 0 1 u3 ;
     0 0 0 1  ]
display(U)
A = [a11 a12 a13 a14 ;
     a21 a22 a23 a24 ;
     a31 a32 a33 a34 ;
     a41 a42 a43 a44 ]

A = triu(A, 0)
display(A)

U * A 
inv(U)

4×4 Matrix{Sym}:
 1  u₁  u₄    0
 0    1  u₂  u₅
 0    0    1  u₃
 0    0    0    1

4×4 Matrix{Sym}:
 a₁₁  a₁₂  a₁₃  a₁₄
    0  a₂₂  a₂₃  a₂₄
    0     0  a₃₃  a₃₄
    0     0     0  a₄₄

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂ - u₄  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
 0     1           -u₂                     u₂⋅u₃ - u₅
 0     0              1                              -u₃
 0     0              0                                 1

In [281]:
e4 = [0, 0, 0, 1]
e3 = [0, 0, 1, 0]


display(U \ [e3 e4])

x1 = U \ e4
x2 = U \ e3
display(x1)
display(x2)
y1 = 1 ./ x1
y1[1:end-1] ./= 2
# y1 = [0,0,0,0]
y2 = 1 ./ x2
y2 ./= 2
y2[end] = 0

# y2 = [0,0,0,0]
# y2[end]=0
# y1 = [y11, y12, y13, y14]
# y2 = [y21, y22, y23, y24]


# U * [x2 x1] * [y2 y1]'
A = [x2 x1] * [y2 y1]'
display(A)
display(inv(U))

triu(A) - inv(U)

# X = [x2 x1]
# UX = U * X


# triu(x2 * (1 ./ x2)', )

# [e3 e4] * [y2 y1]'
# [e4 e3] * [y2 y1]'

4×2 Matrix{Sym}:
 u₁⋅u₂ - u₄  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
          -u₂                     u₂⋅u₃ - u₅
             1                              -u₃
             0                                 1

4-element Vector{Sym}:
 -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
                    u₂⋅u₃ - u₅
                             -u₃
                                1

4-element Vector{Sym}:
 u₁⋅u₂ - u₄
          -u₂
             1
             0

4×4 Matrix{Sym}:
                                                                                 1  …  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
 -u_2/(2*(u_1*u_2 - u_4)) + (u_2*u_3 - u_5)/(2*(-u_1*u_2*u_3 + u_1*u_5 + u_3*u_4))                        u₂⋅u₃ - u₅
               -u_3/(2*(-u_1*u_2*u_3 + u_1*u_5 + u_3*u_4)) + 1/(2*(u_1*u_2 - u_4))                                 -u₃
                                          1/(2*(-u_1*u_2*u_3 + u_1*u_5 + u_3*u_4))                                    1

4×4 Matrix{Sym}:
 1  -u₁  u₁⋅u₂ - u₄  -u₁⋅u₂⋅u₃ + u₁⋅u₅ + u₃⋅u₄
 0     1           -u₂                     u₂⋅u₃ - u₅
 0     0              1                              -u₃
 0     0              0                                 1

4×4 Matrix{Sym}:
 0  …  0
 0     0
 0     0
 0     0

In [ ]:
triu(x1 * (1 ./ x1)')

4×4 Matrix{Sym}:
 1  …  -u₁₁⋅u₂₁⋅u₃₁ + u₁₁⋅u₂₂ + u₁₂⋅u₃₁
 0                            u₂₁⋅u₃₁ - u₂₂
 0                                       -u₃₁
 0                                           1

In [ ]:
triu(x2 * (1 ./ x2)')

4×4 Matrix{Sym}:
 1  -(u_11*u_21 - u_12)/u_21  …  (u_11*u_21 - u_12)*conjugate(zoo)
 0                         1                  -u_21*conjugate(zoo)
 0                         0                        conjugate(zoo)
 0                         0                                     0

In [146]:
println(sympy.latex(triu(x2 * (1 ./ x2)')))

\left[\begin{matrix}1 & \frac{x_{21}}{x_{22}} & \frac{x_{21}}{x_{23}} & \frac{x_{21}}{x_{24}}\\0 & 1 & \frac{x_{22}}{x_{23}} & \frac{x_{22}}{x_{24}}\\0 & 0 & 1 & \frac{x_{23}}{x_{24}}\\0 & 0 & 0 & 1\end{matrix}\right]


ppl (generic function with 1 method)

In [149]:
ppl(A)

\left[\begin{matrix}a_{11} & a_{12} & a_{13} & a_{14}\\0 & a_{22} & a_{23} & a_{24}\\0 & 0 & a_{33} & a_{34}\\0 & 0 & 0 & a_{44}\end{matrix}\right]


In [352]:
n = 100
bw = 2
U = BandedMatrix(rand(n, n), (0, bw))
X = rand(n, bw)
Y = rand(n, bw)




X[end, 1] = 0
Y[end, 1] = 0





En = zeros(n, bw)
En[end-1, 1] = 1
En[end, 2] = 1
En

En_1 = zeros(n, bw)
En_1[end-1-2, 1] = 1
En_1[end-2, 2] = 1
En_1

X * Y'

100×100 Matrix{Float64}:
 0.2211     0.369553   0.160907   …  0.25765    0.207651   0.297148
 0.134764   0.358732   0.148654      0.26225    0.190813   0.31031
 0.374271   0.804387   0.340135      0.577082   0.437572   0.676074
 0.688397   0.734343   0.343262      0.474108   0.446176   0.52229
 1.01495    0.888316   0.432443      0.545807   0.564274   0.581918
 0.856839   0.898106   0.42122    …  0.577567   0.547686   0.634677
 0.395062   0.233114   0.125639      0.123659   0.165418   0.117472
 0.407661   0.229123   0.125316      0.118597   0.165194   0.11016
 0.890082   0.291822   0.194633      0.0946548  0.260358   0.0387796
 0.248768   0.0853812  0.0558453     0.029466   0.0746058  0.014536
 0.435319   0.224752   0.126272   …  0.110946   0.166816   0.0983578
 0.59436    0.978089   0.426738      0.680522   0.550824   0.783944
 0.15808    0.592198   0.239318      0.442716   0.306321   0.529889
 ⋮                                ⋱                        
 0.363675   0.545945   0.241209 

In [334]:
triu(X * Y') * En_1

100×2 Matrix{Float64}:
 0.97004   0.231687
 0.903401  0.190045
 0.456737  0.0177905
 0.485551  0.108317
 0.757351  0.354038
 0.566355  0.04885
 0.527654  0.256755
 1.09299   0.345871
 1.08807   0.283839
 0.2701    0.0154451
 0.185165  0.0652795
 0.647554  0.276655
 0.722145  0.164901
 ⋮         
 0.453826  0.086766
 0.172434  0.0359049
 0.597134  0.12199
 0.336379  0.0858964
 0.122934  0.0114519
 0.904886  0.182803
 0.403828  0.229825
 0.76087   0.160464
 0.454517  0.0294619
 0.0       0.078564
 0.0       0.0
 0.0       0.0

In [337]:
(X * Y')[:, end-3:end-2]

100×2 Matrix{Float64}:
 0.97004   0.231687
 0.903401  0.190045
 0.456737  0.0177905
 0.485551  0.108317
 0.757351  0.354038
 0.566355  0.04885
 0.527654  0.256755
 1.09299   0.345871
 1.08807   0.283839
 0.2701    0.0154451
 0.185165  0.0652795
 0.647554  0.276655
 0.722145  0.164901
 ⋮         
 0.453826  0.086766
 0.172434  0.0359049
 0.597134  0.12199
 0.336379  0.0858964
 0.122934  0.0114519
 0.904886  0.182803
 0.403828  0.229825
 0.76087   0.160464
 0.454517  0.0294619
 0.755129  0.078564
 0.385552  0.0720958
 0.554324  0.0171337

In [343]:
X[end-3:end-2, :] * Y[end-3:end-2, :]'

2×2 Matrix{Float64}:
 0.454517  0.0294619
 0.755129  0.078564

In [344]:
triu(X[end-3:end-2, :]) * Y[end-3:end-2, :]'

2×2 Matrix{Float64}:
 0.454517  0.0294619
 0.657192  0.0203133

In [346]:
triu(X, -n+bw+2) * Y[end-3:end-2, :]' - triu(X * Y') * En_1

100×2 Matrix{Float64}:
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 ⋮         
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.0        0.0
 0.657192  -0.0582507
 0.0        0.0
 0.0        0.0

In [396]:
# X = triu(rand(2, 2))
Y = triu(rand(2, 2))
X = rand(2, 2)
# Y = rand(2, 2)


for i in 1:49
    # X = [X ; triu(rand(2, 2))]
    X = [X ; rand(2, 2)]
    Y = [Y  triu(rand(2, 2))]
    # Y = [Y  rand(2, 2)]
end
Y

X * Y

100×100 Matrix{Float64}:
 0.282983   0.306876   0.300355   0.347896  …  0.499638  0.207396   0.626056
 0.120468   0.13939    0.127864   0.818073     0.951957  0.0882907  0.869461
 0.136947   0.154122   0.145354   0.598074     0.715948  0.100368   0.689696
 0.216157   0.235395   0.229427   0.341331     0.465057  0.15842    0.546242
 0.138175   0.150359   0.146658   0.209455     0.287642  0.101268   0.341316
 0.126476   0.141052   0.13424    0.453883  …  0.552562  0.0926936  0.548351
 0.0761315  0.0903066  0.0808053  0.6868       0.788971  0.0557964  0.702286
 0.369855   0.402097   0.39256    0.532337     0.738692  0.271065   0.888121
 0.249722   0.269875   0.265053   0.23562      0.362146  0.18302    0.488229
 0.238667   0.264351   0.253319   0.717037     0.888826  0.174918   0.909255
 0.449655   0.491224   0.47726    0.828698  …  1.09835   0.32955    1.24309
 0.279247   0.306451   0.296391   0.620946     0.799399  0.204659   0.867658
 0.172028   0.193569   0.182589   0.74874      0.896

In [397]:
X = rand(2,2)
Y = rand(2,2)
Y = triu(Y)
# X = triu(X)

display(triu(X*Y) - triu(X)*triu(Y))
display(triu(X*Y) - triu(X)*Y)
display(triu(X*Y) - X*triu(Y))


2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0908206

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0908206

2×2 Matrix{Float64}:
  0.0      0.0
 -0.32848  0.0

BigFloat

In [42]:
n = 2*100
bw = 2
U = BandedMatrix(rand(n, n), (0, bw))
U += I

display(cond(U))
# for i in 1:n
#     U[i, i] = 1.0
# end
# display(U)


E2 = zeros(n, 2)

E2[end-1:end, :] = [1 0 ; 0 1]
X = U \ E2
Yt = zeros(2, n)
Yt[:, n-1:n] = [1 0 ; 0 1]


# display(X)
for i in n-3 : -2 : 1
    # println((i, i+1))
    Xi = X[i:i+1, :]
    Di = U[i:i+1, i:i+1]
    Yti = inv(Xi) * inv(Di)
    Yt[:, i:i+1] = Yti
    # display(Di)
end 


norm(triu(X * Yt) - inv(U))
# triu(X * Yt) - inv(U)
# Y1 = inv(X1) * inv(D1)

# A = vcat([1 2], [1 2])

6.065175769007365

69.91011711138495