In [152]:
from sympy import *

from IPython.display import display, Latex


In [159]:
n = 5
U = zeros(n, n)
Ut = zeros(n, n)
D = zeros(n, n)
A = zeros(n, n)
X = zeros(n, 2)
Y = zeros(n, 2)
# X = zeros(n, 1)
# Y = zeros(n, 1)
for i in range(n):
    # if X.shape[1] == 1:
    #     exec("x%s = symbols(r'x_{%s}')"%(i+1, i+1))
    #     exec('X[i] = x%s'%(i+1))
    #     exec("y%s = symbols(r'y_{%s}')"%(i+1, i+1))
    #     exec('Y[i] = y%s'%(i+1))
    for j in range(n):
        if X.shape[1] == 1:
            exec("x%s = symbols(r'x_{%s}')"%(i+1, i+1))
            exec('X[i] = x%s'%(i+1))
            exec("y%s = symbols(r'y_{%s}')"%(i+1, i+1))
            exec('Y[i] = y%s'%(i+1))

        elif j < X.shape[1]:
            # print((i,j))
            exec("x%s%s = symbols(r'x_{%s%s}')"%(i+1, j+1, i+1, j+1))
            exec('X[i, j] = x%s%s'%(i+1, j+1))
            exec("y%s%s = symbols(r'y_{%s%s}')"%(i+1, j+1, i+1, j+1))
            exec('Y[i, j] = y%s%s'%(i+1, j+1))

        exec("u%s%s = symbols(r'u_{%s%s}')"%(i+1, j+1, i+1, j+1))
        exec("u%s%st = symbols(r'\\tilde{u}_{%s%s}')"%(i+1, j+1, i+1, j+1))
        exec("a%s%s = symbols(r'a_{%s%s}')"%(i+1, j+1, i+1, j+1))
        if j == i:
            U[i, j] = 1
            exec('Ut[i, j] = u%s%st'%(i+1, j+1))
            exec('D[i, j] = 1 / u%s%st'%(i+1, j+1))

        elif j == i + 1:
            exec('U[i, j] = u%s%s'%(i+1, j+1))
            exec('Ut[i, j] = u%s%st'%(i+1, j+1))
        
        elif j == i + 2:
            exec('U[i, j] = u%s%s'%(i+1, j+1))

        if i <= j:
            exec('A[i, j] = a%s%s'%(i+1, j+1))




def pl(X):
    print(latex(X))
    return 


import numpy as np

display(X @ Y.T)

# display(U @ (X @ Y.T))


pl(X @ Y.T)

# Y[1, 0] = 0
# pl(eye(5)[:, 3:5] @ Y.T)
# eye(5)[:, 3:5] @ Y.T


UU = np.triu(np.random.randn(5,5))
xx = np.random.randn(5,2)
yy = np.random.randn(5,2)


print(np.linalg.norm(UU @ np.triu(xx @ yy.T) - np.triu(UU @ (xx @ yy.T))))


print(UU @ np.triu(xx @ yy.T))
print(np.triu(UU @ (xx @ yy.T)))




AAA = np.triu(np.random.randn(5,5))
BBB = np.triu(np.random.randn(5,5))
BBB = np.random.randn(5,5)


# BBB = xx @ yy.T

np.triu(AAA @ BBB) - AAA @ BBB

# np.linalg.matrix_rank(xx @ yy.T)

# U @ (X @ Y.T)
AAA @ BBB

Matrix([
[x_{11}*y_{11} + x_{12}*y_{12}, x_{11}*y_{21} + x_{12}*y_{22}, x_{11}*y_{31} + x_{12}*y_{32}, x_{11}*y_{41} + x_{12}*y_{42}, x_{11}*y_{51} + x_{12}*y_{52}],
[x_{21}*y_{11} + x_{22}*y_{12}, x_{21}*y_{21} + x_{22}*y_{22}, x_{21}*y_{31} + x_{22}*y_{32}, x_{21}*y_{41} + x_{22}*y_{42}, x_{21}*y_{51} + x_{22}*y_{52}],
[x_{31}*y_{11} + x_{32}*y_{12}, x_{31}*y_{21} + x_{32}*y_{22}, x_{31}*y_{31} + x_{32}*y_{32}, x_{31}*y_{41} + x_{32}*y_{42}, x_{31}*y_{51} + x_{32}*y_{52}],
[x_{41}*y_{11} + x_{42}*y_{12}, x_{41}*y_{21} + x_{42}*y_{22}, x_{41}*y_{31} + x_{42}*y_{32}, x_{41}*y_{41} + x_{42}*y_{42}, x_{41}*y_{51} + x_{42}*y_{52}],
[x_{51}*y_{11} + x_{52}*y_{12}, x_{51}*y_{21} + x_{52}*y_{22}, x_{51}*y_{31} + x_{52}*y_{32}, x_{51}*y_{41} + x_{52}*y_{42}, x_{51}*y_{51} + x_{52}*y_{52}]])

\left[\begin{matrix}x_{11} y_{11} + x_{12} y_{12} & x_{11} y_{21} + x_{12} y_{22} & x_{11} y_{31} + x_{12} y_{32} & x_{11} y_{41} + x_{12} y_{42} & x_{11} y_{51} + x_{12} y_{52}\\x_{21} y_{11} + x_{22} y_{12} & x_{21} y_{21} + x_{22} y_{22} & x_{21} y_{31} + x_{22} y_{32} & x_{21} y_{41} + x_{22} y_{42} & x_{21} y_{51} + x_{22} y_{52}\\x_{31} y_{11} + x_{32} y_{12} & x_{31} y_{21} + x_{32} y_{22} & x_{31} y_{31} + x_{32} y_{32} & x_{31} y_{41} + x_{32} y_{42} & x_{31} y_{51} + x_{32} y_{52}\\x_{41} y_{11} + x_{42} y_{12} & x_{41} y_{21} + x_{42} y_{22} & x_{41} y_{31} + x_{42} y_{32} & x_{41} y_{41} + x_{42} y_{42} & x_{41} y_{51} + x_{42} y_{52}\\x_{51} y_{11} + x_{52} y_{12} & x_{51} y_{21} + x_{52} y_{22} & x_{51} y_{31} + x_{52} y_{32} & x_{51} y_{41} + x_{52} y_{42} & x_{51} y_{51} + x_{52} y_{52}\end{matrix}\right]
2.8877953669649172
[[ 0.38915477  1.74317052  1.11717825  1.26842486 -2.66928521]
 [ 0.          0.35455355 -2.2174258  -1.56964704 -0.61898196]
 [ 0.          0.     

array([[ 1.86936103,  1.31893832,  4.36412246,  2.37935315, -5.30586419],
       [-1.21097208, -3.20438353, -2.8607856 , -2.17312943,  3.64589308],
       [-0.02861524,  0.56522575, -0.01043644, -0.33818148,  0.39575005],
       [ 0.63719989, -2.31368446, -1.04466038,  0.81057855, -0.42012476],
       [-0.64850035,  0.1019958 ,  0.70790544, -0.25559931, -0.20646972]])

In [154]:
X.shape[1]

1

In [155]:
pl(Y.T)

\left[\begin{matrix}y_{1} & y_{2} & y_{3} & y_{4} & y_{5}\end{matrix}\right]


In [156]:
sqrt(512)

16*sqrt(2)

In [157]:
a = symbols("a")
solve(a**2 - 24*a + 16)

[12 - 8*sqrt(2), 8*sqrt(2) + 12]

In [151]:
#代码

from sympy import Function, dsolve, Derivative, symbols, Eq

from sympy.abc import t, a, b, c, g

t = symbols('t')

u0, u1 =symbols('u_0 u_1', cls=Function)

#注意这里的x和y之间的逗号可以省略，即可以写成x, y=symbols('x y', cls=Function)。这行代码等效于x=Function('x')和y=Function('y')

eq=(Eq(Derivative(u0(t), t, 1), a**3*g*u0(t)/c), Eq(Derivative(u1(t), t, 1), a**2*g*(u1(t))**2/(u0(t))**2))



display(eq[0])
display(eq[1])
#注意这里使用了Eq()函数，所以在第一行导入了from sympy import Eq。Eq()函数内的逗号相当于是等于号，等号左边和右边分别为微分方程左边和右边的表达式，如对于本例的第一个微分方程，除了写成Eq(Derivative(x(t), t, 2), 12*(x(t) + y(t)))外，还可以写成Eq(Derivative(x(t), t, 2)- 12*(x(t) + y(t)), 0)，注意这后面的0不能省略。

#同样地，对于第一个例子求解单个微分方程的情况，如果要使用Eq函数，则应该写成eq=Eq(Derivative(x(t), t, 4) - 22*Derivative(x(t), t, 2) - 24*x(t), 0)和result=dsolve(eq)，并且要在第一行代码导入Eq函数。

#如果在该例中，我们不想使用Eq()函数，则上行代码应该写为eq=(Derivative(x(t), t, 2)-12*(x(t) + y(t)), Derivative(y(t), t, 2)- 12*x(t) - 10*y(t))

#简而言之就是，如果要使用Eq函数，则需要写成微分方程等号左右两边的表达式，当右边为0时，也需要写出来；如果不使用Eq函数，则只需要写出微分方程等号左边的表达式，此时等号右边应为0，且不需要写出来。

result=dsolve(eq)

display(result[0])

display(result[1])

Eq(Derivative(u_0(t), t), a**3*g*u_0(t)/c)

Eq(Derivative(u_1(t), t), a**2*g*u_1(t)**2/u_0(t)**2)

Eq(u_0(t), exp(a**3*g*(C2 + t)/c))

Eq(u_1(t), -2*a*exp(2*a**3*g*(C2 + t)/c)/(C1*a*exp(2*a**3*g*(C2 + t)/c) - c))