# MSc Project
## Week 1
### Try to find $u, v$ such that $triu(uv^{T}, 0) = U^{-1}$ where $U$ is a bidiagonal matrix.
#### Directly method

In [1]:
import sympy as sym
import math
import numpy as np
from numpy import random

In [2]:
A, B, C, D, E, F, a, b, c, d, e, f = sym.symbols('A B C D E F alpha beta gamma delta epsilon zeta')
x1, x2, x3, x4 = sym.symbols('x_1 x_2 x_3 x_4')
y1, y2, y3, y4 = sym.symbols('y_1 y_2 y_3 y_4')

In [3]:
U2 =  sym.Matrix(
    [[A, a],
     [0, B]])
U2

Matrix([
[A, alpha],
[0,     B]])

In [4]:
U2i = U2.inv()
U2i

Matrix([
[1/A, -alpha/(A*B)],
[  0,          1/B]])

In [5]:
u2 = sym.Matrix([[x1], [x2]])
vt2 = sym.Matrix([[y1, y2]])
u2*vt2

Matrix([
[x_1*y_1, x_1*y_2],
[x_2*y_1, x_2*y_2]])

Solving
\begin{align*}
x_{1}y_{1} &= \frac{1}{A}\\
x_{1}y_{2} &= -\frac{\alpha}{AB}\\
x_{2}y_{2} &= \frac{1}{B}
\end{align*}
\
Solution
\begin{align*}
x_{2} &= -\frac{Ax_{1}}{\alpha}\\
y_{1} &= \frac{1}{Ax_{1}}\\
y_{2} &= -\frac{\alpha}{ABx_{1}}
\end{align*}
for $x_1 \neq 0$
\
Let $x_1 = 1$, then
\begin{align*}
x_{2} &= -\frac{A}{\alpha}\\
y_{1} &= \frac{1}{A}\\
y_{2} &= -\frac{\alpha}{AB}
\end{align*}


In [6]:
u2 = sym.Matrix([[1], [-A/a]])
vt2 = sym.Matrix([[1/A, -a/(A*B)]])
u2*vt2

Matrix([
[     1/A, -alpha/(A*B)],
[-1/alpha,          1/B]])

In [7]:
U3 =  sym.Matrix(
    [[A, a, 0],
     [0, B, b],
     [0, 0, C]])
U3

Matrix([
[A, alpha,    0],
[0,     B, beta],
[0,     0,    C]])

In [8]:
U3i = U3.inv()
U3i

Matrix([
[1/A, -alpha/(A*B), alpha*beta/(A*B*C)],
[  0,          1/B,        -beta/(B*C)],
[  0,            0,                1/C]])

In [9]:
u3 = sym.Matrix([[x1], [x2], [x3]])
vt3 = sym.Matrix([[y1, y2, y3]])
u3*vt3

Matrix([
[x_1*y_1, x_1*y_2, x_1*y_3],
[x_2*y_1, x_2*y_2, x_2*y_3],
[x_3*y_1, x_3*y_2, x_3*y_3]])

In [10]:
u3 = sym.Matrix([[1], [-A/a], [A*B/(a*b)]])
vt3 = sym.Matrix([[1/A, -a/(A*B), a*b/(A*B*C)]])
u3*vt3

Matrix([
[           1/A, -alpha/(A*B), alpha*beta/(A*B*C)],
[      -1/alpha,          1/B,        -beta/(B*C)],
[B/(alpha*beta),      -1/beta,                1/C]])

In [11]:
U4 =  sym.Matrix(
    [[A, a, 0, 0],
     [0, B, b, 0],
     [0, 0, C, c],
     [0, 0, 0, D]])
U4

Matrix([
[A, alpha,    0,     0],
[0,     B, beta,     0],
[0,     0,    C, gamma],
[0,     0,    0,     D]])

In [12]:
U4i = U4.inv()
U4i

Matrix([
[1/A, -alpha/(A*B), alpha*beta/(A*B*C), -alpha*beta*gamma/(A*B*C*D)],
[  0,          1/B,        -beta/(B*C),          beta*gamma/(B*C*D)],
[  0,            0,                1/C,                -gamma/(C*D)],
[  0,            0,                  0,                         1/D]])

In [13]:
u4 = sym.Matrix([[x1], [x2], [x3], [x4]])
vt4 = sym.Matrix([[y1, y2, y3, y4]])
u4*vt4

Matrix([
[x_1*y_1, x_1*y_2, x_1*y_3, x_1*y_4],
[x_2*y_1, x_2*y_2, x_2*y_3, x_2*y_4],
[x_3*y_1, x_3*y_2, x_3*y_3, x_3*y_4],
[x_4*y_1, x_4*y_2, x_4*y_3, x_4*y_4]])

In [14]:
u4 = sym.Matrix([[1], [-A/a], [A*B/(a*b)], [-A*B*C/(a*b*c)]])
vt3 = sym.Matrix([[1/A, -a/(A*B), a*b/(A*B*C), -a*b*c/(A*B*C*D)]])
u3*vt3

Matrix([
[           1/A, -alpha/(A*B), alpha*beta/(A*B*C), -alpha*beta*gamma/(A*B*C*D)],
[      -1/alpha,          1/B,        -beta/(B*C),          beta*gamma/(B*C*D)],
[B/(alpha*beta),      -1/beta,                1/C,                -gamma/(C*D)]])

In [70]:
random.seed(4396)
def gen_U(n):
    a = random.randn(n-1)
    d = random.randn(n)
    U = np.diag(d, 0) + np.diag(a, 1)
    return U
# Only for no zero in main and upper super diagonal
def U_inv(U):
    n = len(U)
    x = np.zeros(n)
    y = np.zeros(n)
    md = np.diagonal(U, offset = 0)
    md0 = np.diagonal(U, offset = 0)[:n]
    usd = np.diagonal(U, offset = 1)

    for i in range(n):
        # set x1 = 1
        if i == 0:
            x[i] = 1
            y[i] = 1/U[i, i]
        # compute sgn
        sgn = (-1)**(i)
        # compute x
        x[i] = sgn * np.prod(md0[:i]) / np.prod(usd[:i])

        # compute y
        y[i] = sgn * np.prod(usd[:i]) / np.prod(md[:i+1])

    Uinv = np.triu(np.outer(x, y), 0)
    return Uinv

U = (gen_U(4))
# U[1, 2] = 0
Uinv = U_inv(U)
Uinv0 = np.linalg.inv(U)
print(np.linalg.norm(Uinv0 - Uinv))


2.830524433501838e-16


In [16]:
U5 =  sym.Matrix(
    [[A, a, 0, 0, 0],
     [0, B, 0, 0, 0],
     [0, 0, C, c, 0],
     [0, 0, 0, D, 0],
     [0, 0, 0, 0, E]])
U5

Matrix([
[A, alpha, 0,     0, 0],
[0,     B, 0,     0, 0],
[0,     0, C, gamma, 0],
[0,     0, 0,     D, 0],
[0,     0, 0,     0, E]])

In [17]:
U5i = U5.inv()
U5i

Matrix([
[1/A, -alpha/(A*B),   0,            0,   0],
[  0,          1/B,   0,            0,   0],
[  0,            0, 1/C, -gamma/(C*D),   0],
[  0,            0,   0,          1/D,   0],
[  0,            0,   0,            0, 1/E]])

## Week 2
### Try to use back-substitution algorithm for solving $U^{-1}$ from $UX = I$
#### $UX = I \Rightarrow UXe_j = Ie_j \Rightarrow Ux_j = e_j$, where $X = [x_1 \ x_2 \ \cdots \ x_n] = U^{-1}$, $e_j = [0 \ 0 \cdots \ 1 \ \cdots \ 0]^T$ with $1$ in the $j^{th}$ row.

### Solving an upper triangular system, $Ux = b$, $U \in {\mathbb{C}}^{n \times n}$ and $U_{i,j} = 0$ for $i > j$.
#### - $x_n = \frac{b_n}{U_{n,n}}$ 
#### - For $i = n-1, n-2, ..., 1$

In [44]:
def U_inv_backsub(U):
    """
    For finding the inverse of bidiagnal matrix by back subsitution, column by column, Ux_j = e_j
    """
    n = len(U)
    X = np.zeros((n, n))
    # I = np.eye(n)
    for j in range(n):
        if n-1 == j:
            X[n-1, j] = 1 / U[n-1, n-1]
        else:
            X[n-1, j] = 0

        # X[n-1, j] = I[n-1, j] / U[n-1, n-1]

        for i in range(n-2, -1, -1):
            # print(2)
            if i == j:
                X[i, j] = (1 - U[i, i+1] * X[i+1, j]) / U[i,i]
            else:
                X[i, j] = (- U[i, i+1] * X[i+1, j]) / U[i,i]

            # X[i, j] = (I[i, j] - U[i, i+1] * X[i+1, j]) / U[i,i]

    return X

U = (gen_U(4))
# U[1, 2] = 0
Uinv = U_inv_backsub(U)
Uinv0 = np.linalg.inv(U)
print(np.linalg.norm(Uinv0 - Uinv))

0.0


## Week 3
### Try to find the relation between columns of the result from the back-subsitution

In [19]:
d1, d2, d3, d4, d5, d6 = sym.symbols('d_1 d_2 d_3 d_4 d_5 d_6')
a1, a2, a3, a4, a5 = sym.symbols('a_1 a_2 a_3 a_4 a_5')

In [76]:
U61 =  sym.Matrix(
    [[1, a1, 0, 0, 0, 0],
     [0, 1, a2, 0, 0, 0],
     [0, 0, 1, a3, 0, 0],
     [0, 0, 0, 1, a4, 0],
     [0, 0, 0, 0, 1, a5],
     [0, 0, 0, 0, 0, 1]])
U61

Matrix([
[1, a_1,   0,   0,   0,   0],
[0,   1, a_2,   0,   0,   0],
[0,   0,   1, a_3,   0,   0],
[0,   0,   0,   1, a_4,   0],
[0,   0,   0,   0,   1, a_5],
[0,   0,   0,   0,   0,   1]])

In [77]:
U61i = U61.inv()
U61i

Matrix([
[1, -a_1, a_1*a_2, -a_1*a_2*a_3, a_1*a_2*a_3*a_4, -a_1*a_2*a_3*a_4*a_5],
[0,    1,    -a_2,      a_2*a_3,    -a_2*a_3*a_4,      a_2*a_3*a_4*a_5],
[0,    0,       1,         -a_3,         a_3*a_4,         -a_3*a_4*a_5],
[0,    0,       0,            1,            -a_4,              a_4*a_5],
[0,    0,       0,            0,               1,                 -a_5],
[0,    0,       0,            0,               0,                    1]])

In [78]:
# for j in range(5):
#     for i in range(6):
#         print(U6i[i, 5] / U6i[i, j])
for j in range(5):
    print(U61i[0, j] / U61i[0, 5])

-1/(a_1*a_2*a_3*a_4*a_5)
1/(a_2*a_3*a_4*a_5)
-1/(a_3*a_4*a_5)
1/(a_4*a_5)
-1/a_5


In [79]:
x6 = U61i[:, 5]
yt6 = sym.Matrix([[-1/(a1*a2*a3*a4*a5), 1/(a2*a3*a4*a5), -1/(a3*a4*a5), 1/(a4*a5), -1/a5, 1]])
x6*yt6

Matrix([
[                       1,                -a_1,          a_1*a_2, -a_1*a_2*a_3, a_1*a_2*a_3*a_4, -a_1*a_2*a_3*a_4*a_5],
[                  -1/a_1,                   1,             -a_2,      a_2*a_3,    -a_2*a_3*a_4,      a_2*a_3*a_4*a_5],
[             1/(a_1*a_2),              -1/a_2,                1,         -a_3,         a_3*a_4,         -a_3*a_4*a_5],
[        -1/(a_1*a_2*a_3),         1/(a_2*a_3),           -1/a_3,            1,            -a_4,              a_4*a_5],
[     1/(a_1*a_2*a_3*a_4),    -1/(a_2*a_3*a_4),      1/(a_3*a_4),       -1/a_4,               1,                 -a_5],
[-1/(a_1*a_2*a_3*a_4*a_5), 1/(a_2*a_3*a_4*a_5), -1/(a_3*a_4*a_5),  1/(a_4*a_5),          -1/a_5,                    1]])

In [80]:
np.triu(x6*yt6) - U61i

Matrix([
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0]])

In [120]:
def gen_U_week3_onediag(n):
    a = random.randn(n-1)
    U_onediag = np.eye(n) + np.diag(a, 1)
    return U_onediag

# Only for no zero in main and upper super diagonal
def U_inv_week3_onediag(U, FLOP = False):

    n = len(U)
    x = np.zeros(n)
    y = np.zeros(n)
    x[-1] = 1
    y[-1] = 1
    a = np.diagonal(U, offset = 1)
    if not FLOP:
        FLOP = 5 + (n-1)

    for i in range(n-1):
        x[i] = np.prod(-a[i:])
        y[i] = 1 / x[i]
        if not FLOP:
            FLOP = 3 + len(a[i:]) + (len(a[i:])-1)

    Uinv = np.triu(np.outer(x, y), 0)
    return Uinv

U = (gen_U_week3_onediag(10))
# print(U)
Uinv = U_inv_week3_onediag(U)
Uinv0 = np.linalg.inv(U)
print(np.linalg.norm(Uinv0 - Uinv))
# %timeit np.linalg.inv(U)
# %timeit U_inv_week3_onediag(U)

5.241047207555275e-16


In [81]:
d1, d2, d3, d4, d5, d6= sym.symbols('d_1 d_2 d_3 d_4 d_5 d_6')
U6 =  sym.Matrix(
    [[d1, a1, 0, 0, 0, 0],
     [0, d2, a2, 0, 0, 0],
     [0, 0, d3, a3, 0, 0],
     [0, 0, 0, d4, a4, 0],
     [0, 0, 0, 0, d5, a5],
     [0, 0, 0, 0, 0, d6]])
U6

Matrix([
[d_1, a_1,   0,   0,   0,   0],
[  0, d_2, a_2,   0,   0,   0],
[  0,   0, d_3, a_3,   0,   0],
[  0,   0,   0, d_4, a_4,   0],
[  0,   0,   0,   0, d_5, a_5],
[  0,   0,   0,   0,   0, d_6]])

In [82]:
U6i = U6.inv()
U6i

Matrix([
[1/d_1, -a_1/(d_1*d_2), a_1*a_2/(d_1*d_2*d_3), -a_1*a_2*a_3/(d_1*d_2*d_3*d_4), a_1*a_2*a_3*a_4/(d_1*d_2*d_3*d_4*d_5), -a_1*a_2*a_3*a_4*a_5/(d_1*d_2*d_3*d_4*d_5*d_6)],
[    0,          1/d_2,        -a_2/(d_2*d_3),          a_2*a_3/(d_2*d_3*d_4),        -a_2*a_3*a_4/(d_2*d_3*d_4*d_5),          a_2*a_3*a_4*a_5/(d_2*d_3*d_4*d_5*d_6)],
[    0,              0,                 1/d_3,                 -a_3/(d_3*d_4),                 a_3*a_4/(d_3*d_4*d_5),                 -a_3*a_4*a_5/(d_3*d_4*d_5*d_6)],
[    0,              0,                     0,                          1/d_4,                        -a_4/(d_4*d_5),                          a_4*a_5/(d_4*d_5*d_6)],
[    0,              0,                     0,                              0,                                 1/d_5,                                 -a_5/(d_5*d_6)],
[    0,              0,                     0,                              0,                                     0,                                       

In [83]:
for j in range(5):
    print(U6i[0, j] / U6i[0, 5])

-d_2*d_3*d_4*d_5*d_6/(a_1*a_2*a_3*a_4*a_5)
d_3*d_4*d_5*d_6/(a_2*a_3*a_4*a_5)
-d_4*d_5*d_6/(a_3*a_4*a_5)
d_5*d_6/(a_4*a_5)
-d_6/a_5


In [73]:
b1, b2, b3, b4 = sym.symbols('b_1 b_2 b_3 b_4')
U6_tri =  sym.Matrix(
    [[1, a1, b1, 0, 0, 0],
     [0, 1, a2, b2, 0, 0],
     [0, 0, 1, a3, b3, 0],
     [0, 0, 0, 1, a4, b4],
     [0, 0, 0, 0, 1, a5],
     [0, 0, 0, 0, 0, 1]])
U6_tri

Matrix([
[1, a_1, b_1,   0,   0,   0],
[0,   1, a_2, b_2,   0,   0],
[0,   0,   1, a_3, b_3,   0],
[0,   0,   0,   1, a_4, b_4],
[0,   0,   0,   0,   1, a_5],
[0,   0,   0,   0,   0,   1]])

In [95]:
U6i_tri = U6_tri.inv()
U6i_tri

Matrix([
[1, -a_1, a_1*a_2 - b_1, -a_1*a_2*a_3 + a_1*b_2 + a_3*b_1, a_1*a_2*a_3*a_4 - a_1*a_2*b_3 - a_1*a_4*b_2 - a_3*a_4*b_1 + b_1*b_3, -a_1*a_2*a_3*a_4*a_5 + a_1*a_2*a_3*b_4 + a_1*a_2*a_5*b_3 + a_1*a_4*a_5*b_2 - a_1*b_2*b_4 + a_3*a_4*a_5*b_1 - a_3*b_1*b_4 - a_5*b_1*b_3],
[0,    1,          -a_2,                    a_2*a_3 - b_2,                                    -a_2*a_3*a_4 + a_2*b_3 + a_4*b_2,                                                                    a_2*a_3*a_4*a_5 - a_2*a_3*b_4 - a_2*a_5*b_3 - a_4*a_5*b_2 + b_2*b_4],
[0,    0,             1,                             -a_3,                                                       a_3*a_4 - b_3,                                                                                                       -a_3*a_4*a_5 + a_3*b_4 + a_5*b_3],
[0,    0,             0,                                1,                                                                -a_4,                                                                     

In [157]:
U4_tri =  sym.Matrix(
    [[1, a1, b1, 0],
     [0, 1, a2, b2],
     [0, 0, 1, a3],
     [0, 0, 0, 1,]])
U4_tri



Matrix([
[1, a_1, b_1,   0],
[0,   1, a_2, b_2],
[0,   0,   1, a_3],
[0,   0,   0,   1]])

In [156]:
U4i_tri = U4_tri.inv()
U4i_tri
# a, b = sym.symbols('alpha beta')
# a * U4i_tri[:, 3] + b * U4i_tri[:, 2]

Matrix([
[1, -a_1, a_1*a_2 - b_1, -a_1*a_2*a_3 + a_1*b_2 + a_3*b_1],
[0,    1,          -a_2,                    a_2*a_3 - b_2],
[0,    0,             1,                             -a_3],
[0,    0,             0,                                1]])

In [137]:
U4i_tri[:,1]

Matrix([
[-a_1],
[   1],
[   0],
[   0]])

In [154]:
U4i_tri[:2,-1] * (-1/b2)

Matrix([
[-(-a_1*a_2*a_3 + a_1*b_2 + a_3*b_1)/b_2],
[                   -(a_2*a_3 - b_2)/b_2]])

In [160]:
U4i_tri[:2,-2] * (-a3/b2)

Matrix([
[-a_3*(a_1*a_2 - b_1)/b_2],
[             a_2*a_3/b_2]])

In [161]:
U4i_tri[:2,-3]

Matrix([
[-a_1],
[   1]])

In [162]:
U4i_tri[:2,-1] * (-1/b2) + U4i_tri[:2,-2] * (-a3/b2) - U4i_tri[:2,-3]

Matrix([
[a_1 - a_3*(a_1*a_2 - b_1)/b_2 - (-a_1*a_2*a_3 + a_1*b_2 + a_3*b_1)/b_2],
[                                 a_2*a_3/b_2 - 1 - (a_2*a_3 - b_2)/b_2]])

In [164]:
U4i_tri[:1,-1] * (-1/b2) * (1/-a1) + U4i_tri[:1,-2] * (-a3/b2) * (1/-a1) - U4i_tri[:1,-4]

Matrix([[-1 + a_3*(a_1*a_2 - b_1)/(a_1*b_2) + (-a_1*a_2*a_3 + a_1*b_2 + a_3*b_1)/(a_1*b_2)]])

In [116]:
from copy import deepcopy

def gen_Utri_week3_onediag(n):
    a = random.randn(n-1)
    b = random.randn(n-2)
    Utri_onediag = np.eye(n) + np.diag(a, 1) + np.diag(b, 2)
    return Utri_onediag
    
n = 5
U = gen_Utri_week3_onediag(n)

Uinv = np.linalg.inv(U)
rank = np.linalg.matrix_rank(Uinv)
print(rank)
print(Uinv)
Uinvl = deepcopy(Uinv).T

for i in range(n):
    for j in range(n):
        if i>j:
            Uinvl[i, j] = 1 / Uinvl[i, j]

print(Uinvl)

guess = Uinv + Uinvl - np.eye(n)
print(guess)
rank = np.linalg.matrix_rank(guess)
print(rank)
# # for j in range(5):
# # j = 4
# # print(U6i_tri[0, j] / U6i_tri[0, 5])

_, indexes = sym.Matrix(guess).T.rref()
print(indexes)

5
[[ 1.         -1.10989961 -0.20743864  0.36014872  0.40011931]
 [ 0.          1.         -0.21795799 -0.40210657 -0.79688715]
 [ 0.          0.          1.          0.19171954  1.07787982]
 [ 0.          0.          0.          1.          1.55959982]
 [ 0.          0.          0.          0.          1.        ]]
[[ 1.          0.          0.          0.          0.        ]
 [-0.90098239  1.          0.          0.          0.        ]
 [-4.82070261 -4.58804017  1.          0.          0.        ]
 [ 2.77663069 -2.48690292  5.21595232  1.          0.        ]
 [ 2.49925454 -1.25488282  0.92774722  0.64119012  1.        ]]
[[ 1.         -1.10989961 -0.20743864  0.36014872  0.40011931]
 [-0.90098239  1.         -0.21795799 -0.40210657 -0.79688715]
 [-4.82070261 -4.58804017  1.          0.19171954  1.07787982]
 [ 2.77663069 -2.48690292  5.21595232  1.          1.55959982]
 [ 2.49925454 -1.25488282  0.92774722  0.64119012  1.        ]]
5
(0, 1, 2, 3, 4)
