In [1]:
using Pkg
Pkg.status()
using SymPy
using BenchmarkTools, LinearAlgebra, LazyArrays, BandedMatrices

      Status `~/.julia/environments/v1.7/Project.toml`
  [aae01518] BandedMatrices v0.17.0
  [6e4b80f9] BenchmarkTools v1.3.1
  [8e7c35d0] BlockArrays v0.16.18
  [ce91de38] ColorBitstring v0.1.1
  [7073ff75] IJulia v1.23.3
  [5078a376] LazyArrays v0.22.10
  [a3b82374] MatrixFactorizations v0.9.1
  [91a5bcdd] Plots v1.29.0
  [f27b6e38] Polynomials v3.1.4
  [438e738f] PyCall v1.93.1
  [d330b81b] PyPlot v2.10.0
  [295af30f] Revise v3.3.3
  [f8ebbe35] SemiseparableMatrices v0.3.3
  [3cc68bcd] SetRounding v0.2.1
  [24249f21] SymPy v1.1.6
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [8dfed614] Test


In [2]:
function ppl(context)
    println(sympy.latex(context))
end

ppl (generic function with 1 method)

In [94]:
xx0 = symbols("x_(1:6)", real=True)
yy0 = symbols("y_(1:6)", real=True)
uu0 = symbols("u_(1:6)", real=True)
vv0 = symbols("v_(1:6)", real=True)
pp0 = symbols("p_(1:6)", real=True)
qq0 = symbols("q_(1:6)", real=True)
xs = [i for i in xx0]
ys = [i for i in yy0]
us = [i for i in uu0]
vs = [i for i in vv0]
ps = [i for i in pp0]
qs = [i for i in qq0]

xf = rand(6)
yf = rand(6);

In [95]:
Ss = triu(xs * ys', 1) + tril(ys * xs')

5×5 Matrix{Sym}:
 x₁⋅y₁  x₁⋅y₂  x₁⋅y₃  x₁⋅y₄  x₁⋅y₅
 x₁⋅y₂  x₂⋅y₂  x₂⋅y₃  x₂⋅y₄  x₂⋅y₅
 x₁⋅y₃  x₂⋅y₃  x₃⋅y₃  x₃⋅y₄  x₃⋅y₅
 x₁⋅y₄  x₂⋅y₄  x₃⋅y₄  x₄⋅y₄  x₄⋅y₅
 x₁⋅y₅  x₂⋅y₅  x₃⋅y₅  x₄⋅y₅  x₅⋅y₅

In [164]:
display(triu(us * vs'))
display(tril(ps * qs'))
triu(us * vs') * tril(ps * qs')

5×5 Matrix{Sym}:
 u₁⋅v₁  u₁⋅v₂  u₁⋅v₃  u₁⋅v₄  u₁⋅v₅
       0  u₂⋅v₂  u₂⋅v₃  u₂⋅v₄  u₂⋅v₅
       0        0  u₃⋅v₃  u₃⋅v₄  u₃⋅v₅
       0        0        0  u₄⋅v₄  u₄⋅v₅
       0        0        0        0  u₅⋅v₅

5×5 Matrix{Sym}:
 p₁⋅q₁        0        0        0        0
 p₂⋅q₁  p₂⋅q₂        0        0        0
 p₃⋅q₁  p₃⋅q₂  p₃⋅q₃        0        0
 p₄⋅q₁  p₄⋅q₂  p₄⋅q₃  p₄⋅q₄        0
 p₅⋅q₁  p₅⋅q₂  p₅⋅q₃  p₅⋅q₄  p₅⋅q₅

5×5 Matrix{Sym}:
 p₁⋅q₁⋅u₁⋅v₁ + p₂⋅q₁⋅u₁⋅v₂ + p₃⋅q₁⋅u₁⋅v₃ + p₄⋅q₁⋅u₁⋅v₄ + p₅⋅q₁⋅u₁⋅v₅  …  p₅⋅q₅⋅u₁⋅v₅
                   p₂⋅q₁⋅u₂⋅v₂ + p₃⋅q₁⋅u₂⋅v₃ + p₄⋅q₁⋅u₂⋅v₄ + p₅⋅q₁⋅u₂⋅v₅     p₅⋅q₅⋅u₂⋅v₅
                                     p₃⋅q₁⋅u₃⋅v₃ + p₄⋅q₁⋅u₃⋅v₄ + p₅⋅q₁⋅u₃⋅v₅     p₅⋅q₅⋅u₃⋅v₅
                                                       p₄⋅q₁⋅u₄⋅v₄ + p₅⋅q₁⋅u₄⋅v₅     p₅⋅q₅⋅u₄⋅v₅
                                                                         p₅⋅q₁⋅u₅⋅v₅     p₅⋅q₅⋅u₅⋅v₅

In [97]:
triu(xs * ys') * tril(ys * xs')

5×5 Matrix{Sym}:
 x_1^2*y_1^2 + x_1^2*y_2^2 + x_1^2*y_3^2 + x_1^2*y_4^2 + x_1^2*y_5^2  …  x_1*x_5*y_5^2
       x_1*x_2*y_2^2 + x_1*x_2*y_3^2 + x_1*x_2*y_4^2 + x_1*x_2*y_5^2     x_2*x_5*y_5^2
                       x_1*x_3*y_3^2 + x_1*x_3*y_4^2 + x_1*x_3*y_5^2     x_3*x_5*y_5^2
                                       x_1*x_4*y_4^2 + x_1*x_4*y_5^2     x_4*x_5*y_5^2
                                                       x_1*x_5*y_5^2       x_5^2*y_5^2

In [5]:
Sf = triu(xf * yf', 1) + tril(yf * xf')
rank(Sf)

6

In [6]:
inv(Sf)

6×6 Matrix{Float64}:
 -11.241         6.4846       -2.09602e-15  …  -1.23579e-16   1.83847e-15
   6.4846       -1.78968      -3.47178         -3.0938e-17   -9.09585e-16
  -1.91392e-15  -3.47178      -1.50094          6.31215e-16  -3.51476e-16
   6.73981e-16   8.28104e-17   5.92388          2.79054       2.04174e-16
  -2.24043e-16  -4.66405e-17   7.08211e-16     -1.19801      -2.26906
   1.73171e-15  -1.06216e-15   2.29846e-16  …  -2.26906      72.1225

In [7]:
Tridiagonal(inv(Sf))

6×6 Tridiagonal{Float64, Vector{Float64}}:
 -11.241    6.4846     ⋅         ⋅         ⋅         ⋅ 
   6.4846  -1.78968  -3.47178    ⋅         ⋅         ⋅ 
    ⋅      -3.47178  -1.50094   5.92388    ⋅         ⋅ 
    ⋅        ⋅        5.92388  -7.26941   2.79054    ⋅ 
    ⋅        ⋅         ⋅        2.79054  -1.19801  -2.26906
    ⋅        ⋅         ⋅         ⋅       -2.26906  72.1225

In [8]:
isposdef(Tridiagonal(inv(Sf)))

false

In [128]:
n = 6
A = Tridiagonal(rand(n,n))
T = Matrix(A + A' + 100*I)
isposdef(T)
C = cholesky(T)
L = C.L
U = C.U
L * L' ≈ T
U' * U ≈ T

true

In [129]:
include("backsub.jl")
include("invBiU.jl")

invBidiagUxy (generic function with 1 method)

In [130]:
U

6×6 UpperTriangular{Float64, Matrix{Float64}}:
 10.0547   0.140684   0.0        0.0        0.0        0.0
   ⋅      10.0282     0.114973   0.0        0.0        0.0
   ⋅        ⋅        10.0285     0.140468   0.0        0.0
   ⋅        ⋅          ⋅        10.0245     0.153173   0.0
   ⋅        ⋅          ⋅          ⋅        10.0778     0.0876967
   ⋅        ⋅          ⋅          ⋅          ⋅        10.0973

In [131]:
Uinv, xU, yU = invBidiagUxy(U)
Uinv * U ≈ I
Uinv

6×6 Matrix{Float64}:
 0.0994557  -0.00139524   1.59959e-5  -2.24142e-7   3.40675e-9  -2.95883e-11
 0.0         0.0997186   -0.00114324   1.60195e-5  -2.43482e-7   2.11469e-9
 0.0         0.0          0.0997155   -0.00139726   2.1237e-5   -1.84448e-7
 0.0         0.0          0.0          0.0997558   -0.00151619   1.31684e-5
 0.0         0.0          0.0          0.0          0.0992279   -0.000861814
 0.0         0.0          0.0          0.0          0.0          0.0990368

In [132]:
L

6×6 LowerTriangular{Float64, Matrix{Float64}}:
 10.0547      ⋅          ⋅          ⋅          ⋅           ⋅ 
  0.140684  10.0282      ⋅          ⋅          ⋅           ⋅ 
  0.0        0.114973  10.0285      ⋅          ⋅           ⋅ 
  0.0        0.0        0.140468  10.0245      ⋅           ⋅ 
  0.0        0.0        0.0        0.153173  10.0778       ⋅ 
  0.0        0.0        0.0        0.0        0.0876967  10.0973

In [133]:
Linv0, xL, yL = invBidiagUxy(L')
Linv = Linv0'
Linv * L ≈ I
Linv

6×6 adjoint(::Matrix{Float64}) with eltype Float64:
  0.0994557     0.0          0.0          0.0          0.0          0.0
 -0.00139524    0.0997186    0.0          0.0          0.0          0.0
  1.59959e-5   -0.00114324   0.0997155    0.0          0.0          0.0
 -2.24142e-7    1.60195e-5  -0.00139726   0.0997558    0.0          0.0
  3.40675e-9   -2.43482e-7   2.1237e-5   -0.00151619   0.0992279    0.0
 -2.95883e-11   2.11469e-9  -1.84448e-7   1.31684e-5  -0.000861814  0.0990368

In [134]:
# S = triu(xU * yU', 1) + tril(yL * xL')

In [135]:
xL == xU
yL == yU

true

In [160]:
Tinv = Uinv * Linv
# Tinv ≈ triu(xU * yU') * tril(yL * xL')
# Tinv - Tinv'

6×6 Matrix{Float64}:
  0.00989338   -0.00013915    1.59536e-6   …   3.3807e-10  -2.93033e-12
 -0.00013915    0.00994511   -0.000114021     -2.4162e-8    2.09432e-10
  1.59536e-6   -0.000114021   0.00994513       2.10746e-6  -1.82671e-8
 -2.23647e-8    1.59841e-6   -0.000139417     -0.00015046   1.30416e-6
  3.3807e-10   -2.4162e-8     2.10746e-6       0.00984692  -8.53514e-5
 -2.93033e-12   2.09432e-10  -1.82671e-8   …  -8.53514e-5   0.00980829

In [239]:
function getCoef(u, v)
    T = eltype(u)
    n = length(u)
    coef = zeros(T, n)
    coef[n] = u[n]*v[n]
    for i in n-1:-1:1
        coef[i] = coef[i+1] + u[i]*v[i]
    end
    coef
    # println(coef[1] - u'*v)
end

function onepairsym(x, y)
    p = x
    q = x .* getCoef(y,y)
    (p, q)
end

function getSSsym(p, q)
    triu(p * q') + tril(q * p', -1)
    triu(p * q', 1) + tril(q * p')
end

# getCoef(uuu, vvv)
p,q = onepairsym(xU, yU)

getSSsym(p,q) - Tinv

6×6 Matrix{Float64}:
 -1.73472e-18   2.71051e-20  0.0          -6.61744e-24   5.16988e-26  0.0
  2.71051e-20  -1.73472e-18  2.71051e-20   0.0          -3.30872e-24  0.0
  0.0           2.71051e-20  1.73472e-18   0.0           4.23516e-22  0.0
 -6.61744e-24   0.0          0.0          -1.73472e-18   0.0          0.0
  5.16988e-26  -3.30872e-24  4.23516e-22   0.0           1.73472e-18  0.0
  0.0           0.0          0.0           0.0           0.0          0.0

In [225]:
function testf1(x, y, i, j, n)
    if i <= j
        s = y[j].^2
        for k in j+1:n
            s += y[k].^2
        end
    else
        s = y[i].^2
        for k in i+1:n
            s += y[k].^2
        end
    end
    x[i]*x[j]*s
end
function testf11(x, y, i, j, n)
    k = max(i, j)
    x[i]*x[j] * (y[k:n])'*y[k:n]
end
i, j = 3, 5
display(Tinv[i,j])
display(testf11(xU, yU, i, j, n))


function testf2(u, v, p, q, i, j, n)
    if i <= j
        s = p[j] * v[j]
        for k in j+1:n
            s += p[k] * v[k]
        end
    else
        s = p[i] * v[i]
        for k in i+1:n
            s += p[k] * v[k]
        end
    end
    q[j]*u[i]*s
end

function testf22(u, v, p, q, i, j, n)
    k = max(i, j)
    q[j]*u[i] * (p[k:n])'*v[k:n]
end

2.10746093984313e-6

2.1074609398431303e-6

testf22 (generic function with 1 method)

In [233]:
uuu = rand(n)
vvv = rand(n)
ppp = rand(n)
qqq = rand(n)
AAA = triu(uuu * vvv') * tril(ppp * qqq')


for i in 1:n
    for j in 1:n
        println(Tinv[i,j] ≈ testf11(xU, yU, i, j, n))
        # println(AAA[i,j] ≈ testf22(uuu, vvv, ppp, qqq, i, j, n))
    end
end


true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true


In [241]:
function generateSymSS(x, y)
    # tril(ỹ * x̃') + triu(x̃ * ỹ', 1)
    T = eltype(x)
    n = length(x)
    SS = zeros(T, n, n)
    for i in 1:n
        for j in 1:n
            if i <= j
                SS[i,j] = y[j]*x[i]
            else
                SS[i,j] = y[i]*x[j]
            end
        end
    end
    SS
end

xx = rand(6)
yy = rand(6)

generateSymSS(xx,yy) - triu(xx * yy', 1) - tril(yy * xx')

6×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [244]:
@btime generateSymSS(xx,yy);
@btime triu(xx * yy', 1) + tril(yy * xx');

  69.117 ns (1 allocation: 368 bytes)
  281.067 ns (7 allocations: 1.83 KiB)
